### ISSUE TITLE
getting error 

### ISSUE THREAD

**Issue by JonTron1987** [Aveek-Saha/MovieVue#1]
Hello, I was following along with your tutorial and I get an error on the part where you change the template. I get it on the auto-hide and detail. An image of the error is below:

![image](https://user-images.githubusercontent.com/12778501/175794417-56c3ceae-96c2-446f-a103-81f66a6242f9.png)

**Comment by Aveek-Saha** [comment]
What is the error you get when trying to run the app?

**Comment by Aveek-Saha** [comment]
Closing due to no further communication
